name: notebook
channels:
  - conda-forge
dependencies:
  - python=3.9
  - dask
  - rioxarray
  - xarray>=2022.12
  - h5netcdf
  - netcdf4
  - gdal~=3.6
  - geopandas
  - rasterio
  - jupyterlab-git
  - pip
  - jupytext
  - bottleneck
