name: notebook
channels:
  - conda-forge
dependencies:
  - python=3.9
#  - esri::arcgis=2.0.0
## These are needed for jupyterhub functioning
  - jupyterhub-singleuser
  - jupyter-server-proxy
  - jupyter-vscode-proxy
  - ipywidgets
  - jupyterlab=2.2.9
  - jupyterlab-git
  - jupyterlab-favorites
  - jupyter-resource-usage
  - conda-lock
  - code-server >=3.2
## needed for installing jupyterlab-widgets
  - nodejs
