name: 00 - 🧹 Remove Expired Workflow Runs

on:
  # schedule: [{ cron: "30 1 * * *" }] # Schedule to run the workflow every day at 1:30 AM
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  clean:
    name: Remove Expired Workflow Runs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action Code
        uses: actions/checkout@v4

      - name: Set Lower Case Owner Name
        run: echo "OWNER_LC=${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]' | awk -F "=" '{print "OWNER_LC="$2}' >> $GITHUB_ENV

      - name: Run Delete Script
        run: sh ./00_delete_workflow_runs.sh $OWNER_LC ${{ github.event.repository.name }}
        working-directory: .github/actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
