name: 01 - v2 Discover and Build Docker Images
on:
  workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Find Dockerfiles
        id: find
        run: |
          find images -name Dockerfile | sed 's/\/Dockerfile//' | sed 's/^/.\//' > dockerfile_paths.txt

      - name: Create JSON matrix
        id: generate-matrix
        run: |
          jq -R . < dockerfile_paths.txt | jq -s . > dockerfile_paths.json
          cat dockerfile_paths.json  # Debug step

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dockerfile-paths
          path: dockerfile_paths.json

  call-reusable-workflow:
    needs: generate-matrix
    uses: ./.github/workflows/reusable-build-and-publish-v2.yml
    with:
      artifact_name: dockerfile-paths
      repository: ${{ github.repository }}
