name: 02 - Discover and Build Draft Docker Images
on:
##  push:
##    branches:
##      - main
##    paths:
##      - 'draft_images/**'
##      - '.github/workflows/02-main-build-all-draft-images.yml'
  workflow_dispatch:
jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Find Dockerfiles
        id: find
        run: |
          find draft_images -name Dockerfile | sed 's/\/Dockerfile//' > dockerfile_paths.txt

      - name: Create JSON matrix
        id: matrix
        run: |
          paths=$(cat dockerfile_paths.txt | jq -R . | jq -s .)
          echo "paths=${paths}" >> $GITHUB_ENV

      - name: Upload matrix file
        uses: actions/upload-artifact@v3
        with:
          name: dockerfile-matrix
          path: dockerfile_paths.txt

  call-reusable-workflow:
    needs: generate-matrix
    uses: ./.github/workflows/reusable-build-and-publish.yml
    with:
      dockerfile_paths: ${{ fromJson(needs.generate-matrix.outputs.paths) }}
      registry: ghcr.io
      repository: ${{ github.repository }}