name: Docker Image CI openscapes-python
# To use this template, change the env variables
# IMAGE_NAME this should be the same name as the folder in which the Dockerfile is
# IMAGE_TAG whatever tag you want to automatically be used
env:
  IMAGE_NAME: openscapes-python
  IMAGE_TAG: latest
  
on:
  workflow_dispatch: null
  push:
    branches: main
    paths: 
      - 'images/openscapes-python/**'
      - '.github/workflows/docker-image-openscapes-python.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'nmfs-opensci/container-images'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the Docker image
        if: github.repository == 'nmfs-opensci/container-images'
        run: |
          docker build images/openscapes-python -f images/openscapes-python/Dockerfile  --tag ghcr.io/nmfs-opensci/container-images/openscapes-python:latest
      - name: Publish
        if: github.repository == 'nmfs-opensci/container-images'
        run: |
          docker push ghcr.io/nmfs-opensci/container-images/openscapes-python:latest
