name: Docker Image CI py-rocket-base
on:
  workflow_dispatch: null
  push:
    branches: main
    paths: 
      - 'images/py-rocket-base/**'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'nmfs-opensci/container-images'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the Docker image
        if: github.repository == 'nmfs-opensci/container-images'
        run: |
          docker build images/py-rocket-base -f images/py-rocket-base/Dockerfile  --tag ghcr.io/nmfs-opensci/container-images/py-rocket-base:latest
      - name: Publish
        if: github.repository == 'nmfs-opensci/container-images'
        run: |
          docker push ghcr.io/nmfs-opensci/container-images/py-rocket-base:latest

