name: Docker Image CI test
# To use this template, change the env variables
# IMAGE_NAME this should be the same name as the folder in which the Dockerfile is
# IMAGE_TAG whatever tag you want to automatically be used
env:
  IMAGE_NAME: test
  IMAGE_TAG: test
  IMAGE_BRANCH: main
  IMAGE_DIR: draft_images
  
on:
  workflow_dispatch: null
  push:
    branches: main
    paths: 
      - 'draft_images/test/**'
      - '.github/workflows/docker-image-test.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'nmfs-opensci/container-images'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the Docker image
        if: github.repository == 'nmfs-opensci/container-images'
        run: |
          docker buildx create \
            --name container \
            --driver=docker-container
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --builder container $IMAGE_DIR/$IMAGE_NAME \
            -f $IMAGE_DIR/$IMAGE_NAME/Dockerfile \
            --tag ghcr.io/nmfs-opensci/container-images/$IMAGE_NAME:$IMAGE_TAG \
            --tag ghcr.io/nmfs-opensci/container-images/$IMAGE_NAME:latest \
            --push
#      - name: Publish
#        if: github.repository == 'nmfs-opensci/container-images'
#        run: |
#          docker push ghcr.io/nmfs-opensci/container-images/$IMAGE_NAME:$IMAGE_TAG
#          docker push ghcr.io/nmfs-opensci/container-images/$IMAGE_NAME:latest

