name: Docker Image CI
on:
  workflow_dispatch: null
  push:
    paths: 
      - '.devcontainer/py-rocket/**'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'nmfs-opensci/container-images'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the Docker image
        if: github.repository == 'nmfs-opensci/container-images'
        run: |
          docker build .devcontainer/py-rocket -f .devcontainer/py-rocket/conda.Dockerfile  --tag ghcr.io/nmfs-opensci/container-images/py-rocket:conda
      - name: Publish
        if: github.repository == 'nmfs-opensci/container-images'
        run: |
          docker push ghcr.io/nmfs-opensci/container-images/py-rocket:conda

