name: Docker Image CI base notebook
on:
  workflow_dispatch: null
  push:
    paths: 
      - 'images/jupyter-base-notebook/**'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'nmfs-opensci/container-images'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the Docker image
        if: github.repository == 'nmfs-opensci/container-images'
        run: |
          docker build images/jupyter-base-notebook -f images/jupyter-base-notebook/Dockerfile  --tag ghcr.io/nmfs-opensci/container-images/jupyter-base-notebook:latest
      - name: Publish
        if: github.repository == 'nmfs-opensci/container-images'
        run: |
          docker push ghcr.io/nmfs-opensci/container-images/jupyter-base-notebook:latest

