name: Docker Image CI r-geospatial-sdm
env:
  IMAGE_NAME: r-geospatial-sdm
  IMAGE_TAG: 4.4
on:
  workflow_dispatch: null
  push:
    branches: main
    # main path plus the nmfs-opensci-python-base if that is used.
    paths: 
      - 'images/py-rocket-base/**'
      - 'images/r-geospatial-sdm/**'
      - '.github/workflows/docker-image-r-geospatial-sdm.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'nmfs-opensci/container-images'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the Docker image
        if: github.repository == 'nmfs-opensci/container-images'
        run: |
          docker build images/$IMAGE_NAME -f images/$IMAGE_NAME/Dockerfile  --tag ghcr.io/nmfs-opensci/container-images/$IMAGE_NAME:$IMAGE_TAG   --tag ghcr.io/nmfs-opensci/container-images/$IMAGE_NAME:latest
      - name: Publish
        if: github.repository == 'nmfs-opensci/container-images'
        run: |
          docker push ghcr.io/nmfs-opensci/container-images/$IMAGE_NAME:$IMAGE_TAG
          docker push ghcr.io/nmfs-opensci/container-images/$IMAGE_NAME:latest

