name: 00-Process Matrix and Build Docker Images

on:
  workflow_run:
    workflows: ["Generate Matrix and Upload Artifact"]
    types:
      - completed

jobs:
  process-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        folder: []

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dockerfile-paths
          path: .

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]' | awk -F "=" '{print "OWNER_LC="$2}' >> $GITHUB_ENV

      - name: Read matrix from artifact
        id: read-matrix
        run: |
          matrix=$(cat dockerfile_paths.json)
          echo "matrix=${matrix}" >> $GITHUB_ENV
          echo "matrix=${matrix}" >> $GITHUB_ENV_PATHS

      - name: Setup matrix for each folder
        run: |
          folders=$(jq -r '.[]' <<< ${{ env.matrix }})
          echo "folders=${folders}" >> $GITHUB_ENV
          for folder in $folders; do
            echo "folder=${folder}" >> $GITHUB_ENV
          done
          echo "folders=$(jq -r '.[]' <<< ${{ env.matrix }})" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=$(basename ${{ matrix.folder }})
          echo "Building and pushing $IMAGE_NAME"
          docker build ${{ matrix.folder }} -f ${{ matrix.folder }}/Dockerfile --tag ghcr.io/${OWNER_LC}/${IMAGE_NAME}:latest --tag ghcr.io/${OWNER_LC}/${IMAGE_NAME}:${{ github.sha }}
          docker push ghcr.io/${OWNER_LC}/${IMAGE_NAME}:latest
          docker push ghcr.io/${OWNER_LC}/${IMAGE_NAME}:${{ github.sha }}