name: v2 Reusable Build and Publish Docker Images
on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
      repository:
        required: true
        type: string
jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: .

      - name: Read paths and set output
        id: read-paths
        run: |
          paths=$(cat dockerfile_paths.json)
          echo "::set-output name=paths::${paths}"

  build-and-push:
    runs-on: ubuntu-latest
    needs: download-artifact
    permissions: write-all
    strategy:
      matrix:
        folder: ${{ fromJson(needs.download-artifact.outputs.paths) }}
    steps:
      - uses: actions/checkout@v4

      - name: Set lower case owner name
        run: echo "OWNER_LC=${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]' | awk -F "=" '{print "OWNER_LC="$2}' >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=$(basename ${{ matrix.folder }})
          echo "Building and pushing $IMAGE_NAME"
          docker build ${{ matrix.folder }} -f ${{ matrix.folder }}/Dockerfile --tag ghcr.io/${OWNER_LC}/${IMAGE_NAME}:latest --tag ghcr.io/${OWNER_LC}/${IMAGE_NAME}:${{ github.sha }}
          docker push ghcr.io/${OWNER_LC}/${IMAGE_NAME}:latest
          docker push ghcr.io/${OWNER_LC}/${IMAGE_NAME}:${{ github.sha }}